apiVersion: v1
kind: Secret
metadata:
  name: wireguard
type: Opaque
stringData:
  server-config: |
    [Interface]
    PrivateKey = {{ .Values.privateKey }}
    ListenPort = 51820
    Address = {{ .Values.address }}

    {{- range $name, $peer := .Values.peers }}
    [Peer]
    # {{ $name }}
    PublicKey = {{ $peer.publicKey }}
    AllowedIPs = {{ $peer.ip }}
    {{- end }}
